### PR TITLE
Added ability to assign labels to cards during creation

### PR DESCRIPTION
**Pull request by up_the_irons**

### CODE REVIEW

**Comment by mheap** [comment]
@up_the_irons Do you think supplying IDs is reasonable, or do you think we should support named labels too?

**Comment by up_the_irons** [comment]
Named labels would be a great addition.  But having the option for
IDs would allow one to be very granular in their assignments, in
case they change label names, etc... in the future, for example.
Their scripts would not break and the correct canonical label would
still be used.

-- 
Garry Dolley
ARP Networks, Inc. | https://arpnetworks.com | +1 855 444-3145
Data center solutions in Los Angeles and Frankfurt, Germany
Member Los Angeles County REACT, Unit 336 | AG6QQ, WQGK336
Blog http://scie.nti.st

**Comment by mheap** [comment]
I'll merge this in now as it's a useful feature. I do think named labels would be useful. Is there any way we could detect if it's a name or an ID automatically?

**Comment by up_the_irons** [comment]
I actually came across this issue already with board names.  I changed the name of one of my boards, and my scripts had to be updated to reflect the change, even though the board is the same.  IDs could have been useful there, for example.

**Comment by up_the_irons** [comment]
I think to detect if the supplied label is an ID, we could ask the API for a label with that ID, and if it comes back, then yup, it's a label. ;)  However, this may introduce more API calls than it is worth.

**Comment by mheap** [comment]
Could we invert that logic? Instead of asking the API, check if we have a label name locally in our translation and if not, assume that it's an ID?

**Comment by up_the_irons** [comment]
Sounds reasonable. :+1:

**Pull request merged**
