### PR TITLE
Fixes an error in the documentation

### PR DESCRIPTION
**Pull request by ksk100**
(Looks like my copy of Atom has been messing with some of the whitespace; I'll take a look at my settings on that).

### CODE REVIEW

**Comment by mheap** [comment]
@ksk100 Is searching for all boards that contain a string the correct behaviour for `close-board`? Would we be better matching `add-board` behaviour where it's exact and add another method, `fuzzy-close-board` to do what this does?

**Comment by ksk100** [comment]
Good question.

One reason why I did it like this (aside from it also being more useful) was that actually even specifying the full title wouldn't necessarily be exact (in the sense of matching just one) because multiple boards can have the same name.  The app would have to start displaying the IDs of boards to enable that kind of exactness.

There is a similar issue with `delete-card`.  That command requires an exact match, and if there are more than one, then it prints a list and requires you to select which one.  I thought that was of limited usefulness because it's not clear from such a list which card is which - the order isn't guaranteed to match; `trello-cli` displays the cards in the order they were when the board/card cache was last refreshed, and so if they've changed by then, the order won't match that of the actual board.

Still, I suppose it might be a good idea if `close-board` matched the behaviour of `delete-card`, even if there was another command such as `close-boards` which does what is now happening (I'd definitely like a non-interactive version of the command).

**Comment by ksk100** [comment]
ps: I did start to think about how best to display IDs throughout the app, but I kind of forgot about it.

**Comment by mheap** [comment]
I'll merge this for now as the behaviour's already in there. It would be nice to find a way to support exact and fuzzy matching in future

**Pull request merged**
